{
  t=findException(t);
  return (t instanceof CallDroppedException);
}
