{
  if (exception instanceof ConnectException) {
    return (ConnectException)new ConnectException("Call to " + addr + " failed on connection exception: "+ exception).initCause(exception);
  }
 else   if (exception instanceof SocketTimeoutException) {
    return (SocketTimeoutException)new SocketTimeoutException("Call to " + addr + " failed because "+ exception).initCause(exception);
  }
 else {
    return (IOException)new IOException("Call to " + addr + " failed on local exception: "+ exception).initCause(exception);
  }
}
