{
  try {
    verify();
  }
 catch (  Throwable ex) {
    this.ex=ex;
    stopper.stop("caught exception");
  }
}
