{
  for (  Map.Entry<HRegionLocation,MultiAction<Row>> e : actionsByServer.entrySet()) {
    final HRegionLocation loc=e.getKey();
    final MultiAction<Row> multiAction=e.getValue();
    incTaskCounters(multiAction.getRegions(),loc.getServerName());
    Runnable runnable=Trace.wrap("AsyncProcess.sendMultiAction",new Runnable(){
      @Override public void run(){
        MultiResponse res;
        try {
          MultiServerCallable<Row> callable=createCallable(loc,multiAction);
          try {
            res=createCaller(callable).callWithoutRetries(callable);
          }
 catch (          IOException e) {
            receiveGlobalFailure(initialActions,multiAction,loc,numAttempt,e,errorsByServer);
            return;
          }
catch (          Throwable t) {
            LOG.error("#" + id + ", Caught throwable while calling. This is unexpected."+ " Retrying. Server is "+ loc.getServerName()+ ", tableName="+ tableName,t);
            receiveGlobalFailure(initialActions,multiAction,loc,numAttempt,t,errorsByServer);
            return;
          }
          receiveMultiAction(initialActions,multiAction,loc,res,numAttempt,errorsByServer);
        }
  finally {
          decTaskCounters(multiAction.getRegions(),loc.getServerName());
        }
      }
    }
);
    try {
      this.pool.submit(runnable);
    }
 catch (    RejectedExecutionException ree) {
      decTaskCounters(multiAction.getRegions(),loc.getServerName());
      LOG.warn("#" + id + ", the task was rejected by the pool. This is unexpected."+ " Server is "+ loc.getServerName(),ree);
      receiveGlobalFailure(initialActions,multiAction,loc,numAttempt,ree,errorsByServer);
    }
  }
}
