{
  LOG.error(prefix("Received unexpected KeeperException, re-throwing exception"),ke);
  throw ke;
}
