{
  try {
    latch.await();
  }
 catch (  InterruptedException e) {
    throw (InterruptedIOException)new InterruptedIOException().initCause(e);
  }
  if (exception != null) {
    throw exception;
  }
}
