{
  throw new DoNotRetryIOException("Failing for test");
}
