{
  try {
    super.replicate(replicateContext);
    doAssert(row);
  }
 catch (  Exception e) {
    ex.set(e);
  }
  return true;
}
